pipeline {
    agent any
    stages {
        stage("Start Pull Latest Image") {
            steps {
                bat "docker pull ahmedhakem/cucumber-docker:cucumber-docker"
            }
        }
        stage("Start Grid") {
            steps {
                bat "docker-compose up -d hub"
            }
        }
        stage("Run Firefox Tests") {
            steps {
                bat "docker-compose up -d firefox"
                bat "docker-compose up testng-firefox"
                bat "move testng_results\\cucumberReports.json testng_results\\cucumberReports\\firefox_cucumber_report.json" // Rename the report file
            }
        }
        stage("Run Chrome Tests") {
            steps {
                bat "docker-compose up -d chrome"
                bat "docker-compose up testng-chrome"
                bat "move testng_results\\cucumberReports.json testng_results\\cucumberReports\\chrome_cucumber_report.json" // Rename the report file
            }
        }
        stage("Run Edge Tests") {
            steps {
                bat "docker-compose up -d edge"
                bat "docker-compose up testng-edge"
                bat "move testng_results\\cucumberReports.json testng_results\\cucumberReports\\edge_cucumber_report.json" // Rename the report file
            }
        }
        stage("reporting") {
            steps {
                extentReports([
                    extentFiles: 'extent-report.html',
                    reportTitle: 'My Test Report',
                    reportName: 'my-test-report',
                    reportFiles: 'test-out/ExtentReport/*/spark.html'
                ])
            }
        }    
    }
    post {
        always {
            steps {
               
        }
    }
     
    }


}
