pipeline {
    agent any
    stages {
        stage("Start Pull Latest Image") {
            steps {
                bat "docker pull ahmedhakem/cucumber-docker:cucumber-docker"
            }
        }
        stage("Start Grid") {
            steps {
                bat "docker-compose up -d hub"
            }
        }
        stage("Run Firefox Tests") {
            steps {
                bat "docker-compose up -d firefox"
                bat "docker-compose up testng-firefox"
                bat "set mypath=%cd%"
                bat "@echo %mypath%"
                dir('test-output') {
                    bat 'dir'
                }
                bat "move testng_results\\cucumberReports.json testng_results\\cucumberReports\\firefox.json" // Rename the report file
                cucumber buildStatus: 'null', customCssFiles: '', customJsFiles: '', failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, 
                jsonReportDirectory: "testng_results/cucumberReports", fileIncludePattern: '', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
            }
        }

    }
    post {
        always {
            script {
                def jsonFiles = findFiles(glob: 'testng_results/**/*.json')
                jsonFiles.each { jsonFile ->
                    def reportDir = jsonFile.path.replaceAll('.json', '')
                    cucumber buildStatus: 'null', customCssFiles: '', customJsFiles: '', failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1,
                    jsonReportDirectory: reportDir + '_cucumber_report.json', fileIncludePattern: '**/*.json', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
                }
            }
        }
    }
}
